[package]
name = "lasso"
version = "0.2.3"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Kixiron/lasso"
documentation = "https://docs.rs/lasso"
authors = ["Chase Wilson <contact@chasewilson.dev>"]
keywords = ["interner", "intern", "string", "str", "symbol"]
description = """A multithreaded and single threaded string interner that allows strings to be cached with a
minimal memory footprint, associating them with a unique key that can be used to retrieve them at any time.
"""
readme = "README.md"
categories = ["data-structures", "concurrency", "no-std"]
edition = "2018"

[features]
default = []
multi-threaded = ["dashmap", "hashbrown"]
no-std = ["ahasher", "hashbrown-table", "dashmap/no_std"]
hashbrown-table = ["hashbrown"]
ahasher = ["ahash"]
nightly = []
serialize = ["serde"]

# Provides a concurrent hashmap, enabled with the `multi-threaded` feature
[dependencies.dashmap]
version = "3.11.1"
features = ["raw-api"]
optional = true

# Provides a no_std hasher, enabled with the `no-std` feature
[dependencies.ahash]
version = "0.3.5"
optional = true

# Provides a no_std hashmap, enabled with the `no-std` feature
[dependencies.hashbrown]
version = "0.7.2"
optional = true

# Allows {de}serialization of Spurs
[dependencies.serde]
version = "1.0.105"
features = ["derive"]
optional = true

# Benchmarking
[dev-dependencies.criterion]
version = "0.3.2"

# Benchmarking
[dev-dependencies.lazy_static]
version = "1.4.0"

# Cross-hash comparisons with benchmarking
[dev-dependencies.ahash]
version = "0.3.5"

# Cross-hash comparisons with benchmarking
[dev-dependencies.fxhash]
version = "0.2.1"

# Cross-interner comparsions with benchmarking
[dev-dependencies.string-interner]
version = "0.7.1"

# Testing serialization
[dev-dependencies.serde_json]
version = "1.0.53"

[[bench]]
name = "single_threaded"
harness = false

[[bench]]
name = "multi_threaded"
harness = false

[[bench]]
name = "reader"
harness = false

[[bench]]
name = "resolver"
harness = false

[[bench]]
name = "string_interner"
harness = false

[package.metadata.docs.rs]
features = ["multi-threaded"]
targets = ["x86_64-unknown-linux-gnu"]
