[package]
name = "lasso"
version = "0.1.2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Kixiron/lasso"
documentation = "https://docs.rs/lasso"
authors = ["Chase Wilson <contact@chasewilson.dev>"]
keywords = ["interner", "intern", "string", "str", "symbol"]
description = """A multithreaded and single threaded string interner that allows strings to be cached with a
minimal memory footprint, associating them with a unique key that can be used to retrieve them at any time.
"""
readme = "README.md"
categories = ["data-structures", "concurrency", "no-std"]
edition = "2018"

[[bench]]
name = "single_threaded"
harness = false

[[bench]]
name = "multi_threaded"
harness = false

[[bench]]
name = "reader"
harness = false

[[bench]]
name = "resolver"
harness = false

[[bench]]
name = "string_interner"
harness = false

[features]
default = ["multi-threaded"]
multi-threaded = ["dashmap"]
no_std = [
    "ahasher",
    "hashbrown-table",
    "dashmap/no_std",
]
hashbrown-table = ["hashbrown"]
ahasher = ["ahash"]
bench = []

[dependencies.dashmap]
version = "3.9.1"
features = ["raw-api"]
optional = true

[dependencies.ahash]
version = "0.3.2"
optional = true

[dependencies.hashbrown]
version = "0.7.1"
optional = true

[dev-dependencies.criterion]
version = "0.3.1"

[dev-dependencies.lazy_static]
version = "1.4.0"

[dev-dependencies.ahash]
version = "0.3.2"

[dev-dependencies.fxhash]
version = "0.2.1"

[dev-dependencies.string-interner]
version = "0.7.1"
