[package]
name = "lasso"
version = "0.1.2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Kixiron/lasso"
documentation = "https://docs.rs/lasso"
authors = ["Chase Wilson <contact@chasewilson.dev>"]
keywords = ["interner", "intern", "string", "str", "symbol"]
description = """A concurrent string interner that allows strings to be cached with a minimal
memory footprint, allowing them with a unique key that can be used to retrieve them at any time.
"""
readme = "README.md"
categories = ["data-structures"]
edition = "2018"

[features]
default = ["ahasher"]
ahasher = ["ahash"]

[dependencies.dashmap]
version = "3.9.0"
features = ["raw-api"]

[dependencies.ahash]
version = "0.3.2"
optional = true

[dev-dependencies.ahash]
version = "0.3.2"
